### ISSUE TITLE
Does this library can detect and fix emails that can only be used by companies' employees? 

### ISSUE THREAD

**Issue by YuxiaZhang-BIT** [mailcheck/pymailcheck#4]
Does this library can detect and fix emails that can only be used by companies' employees, such as 'redhat.com'?

**Comment by sebst** [comment]
By default, it checks against `DOMAINS` as defined [here](https://github.com/mailcheck/pymailcheck/blob/master/pymailcheck/__init__.py#L10).

You can add corporate domains like this:

```
>>> pymailcheck.suggest("test@contosl.com")
False
>>> custom_domains = pymailcheck.DOMAINS.union(("example.com", "contoso.com"))
>>> pymailcheck.suggest("test@contosl.com", domains=custom_domains)
{'domain': 'contoso.com', 'full': 'test@contoso.com', 'address': 'test'}
```

However, you must provide these domains on your own, this does not check "live" against DNS or Whois or other databases.
